// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiEDheP6f_HU2ePlV3TKJ93Y1YablXGRo',
    appId: '1:894030757405:web:e30f30bb85dd42dd7e50f4',
    messagingSenderId: '894030757405',
    projectId: 'fitness-cb334',
    authDomain: 'fitness-cb334.firebaseapp.com',
    storageBucket: 'fitness-cb334.firebasestorage.app',
    measurementId: 'G-M61Q7BMRKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQqgV1-4Yp2pKnCcULjT0SSTY1C_-Etc0',
    appId: '1:894030757405:android:93112a1e916303817e50f4',
    messagingSenderId: '894030757405',
    projectId: 'fitness-cb334',
    storageBucket: 'fitness-cb334.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACXCx2uqAA8YT-avdCCHn02z7FT4cjJD4',
    appId: '1:894030757405:ios:b9ad933d0a7216947e50f4',
    messagingSenderId: '894030757405',
    projectId: 'fitness-cb334',
    storageBucket: 'fitness-cb334.firebasestorage.app',
    iosBundleId: 'com.example.fitnessProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACXCx2uqAA8YT-avdCCHn02z7FT4cjJD4',
    appId: '1:894030757405:ios:b9ad933d0a7216947e50f4',
    messagingSenderId: '894030757405',
    projectId: 'fitness-cb334',
    storageBucket: 'fitness-cb334.firebasestorage.app',
    iosBundleId: 'com.example.fitnessProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiEDheP6f_HU2ePlV3TKJ93Y1YablXGRo',
    appId: '1:894030757405:web:6ddff08c429aa8ea7e50f4',
    messagingSenderId: '894030757405',
    projectId: 'fitness-cb334',
    authDomain: 'fitness-cb334.firebaseapp.com',
    storageBucket: 'fitness-cb334.firebasestorage.app',
    measurementId: 'G-0H9HGBL887',
  );
}
